$(document).ready(function(){
	require('materialize-tags/dist/js/materialize-tags.min');
	$('.sidenav').sidenav();
	$('.dropdown-trigger').dropdown({
		coverTrigger:false,
	});
	 $('select').formSelect({
	 	coverTrigger:false,
	 });
 });